name: flutter_course_project
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  keyboard_visibility: ^0.5.2
  http: ^0.12.2
  path: ^1.7.0
  assets_audio_player: ^2.0.13

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/lei.jpg
    - assets/images/X.jpg
    - assets/images/O.jpg
    - assets/images/transparent.jpg
    - assets/audio/ciao.mp3


